- name: Add user
  hosts: host-list
  remote_user: vagrant
  gather_facts: true
  become: yes
  tasks:
    - name: Add group "admins" to remote server
      group:
        name: admins
        gid: 2010
        state: present

    - name: Add user "sernowuser" to remote server
      user: 
        name: sernowadmin
        comment: "Privileged User"
        uid: 2001
        group: admins
        append: yes
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa