- name: Copy file
  hosts: host-list
  remote_user: vagrant
  gather_facts: true
  tasks:
  - name: Before Ansible 2.3, option 'dest', 'destfile' or 'name' was used instead of 'path'
    replace:
      path: /etc/hosts
      regexp: '(\s+)old\.host\.name(\s+.*)?$'
      replace: '\1new.host.name\2'